# Development environment reusing production and just adding mounts for docker-sync
version: "2"

services:
  appdata:
    volumes:
      - appdata-magento2:/var/www/html

      # Host mounts with performance penalty, only put what is necessary here
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/etc:/var/www/html/app/etc:delegated
      #- ./src/auth.json:/var/www/html/auth.json:delegated
      #- ./src/composer.json:/var/www/html/composer.json:delegated
      #- ./src/composer.lock:/var/www/html/composer.lock:delegated
      #- ./src/pub:/var/www/html/pub:delegated
      #- ./src/var/log:/var/www/html/var/log:delegated
      #- ./src/var/report:/var/www/html/var/report:delegated
